blockExoticSubdeps: true # cspell:disable-line

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days in minutes

allowBuilds:
  # Not a direct dependency
  esbuild: false # cspell:disable-line
