# shamefullyHoist: true
saveExact: true

minimumReleaseAge: 960 # 16 hours in minutes
minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days in minutes
trustPolicyExclude: # []
  - '@humanwhocodes/momoa@3.3.12' # cspell:disable-line

audit:
  ignore: []
  ignorePrune: true

allowBuilds:
  esbuild@0.28.2: false
  lefthook@2.1.10: true
  unrs-resolver@1.12.2: false

dedupePeers: true
strictPeerDependencies: false
