blockExoticSubdeps: true # cspell:disable-line

minimumReleaseAge: 960 # 16 hours in minutes
# minimumReleaseAgeExclude: []

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days in minutes

strictDepBuilds: true
allowBuilds:
  # core-js: false # Donation message
  esbuild: false # Not a direct dependency
  lefthook: true
  unrs-resolver: false # cspell:disable-line


# overrides: {}
